### ISSUE TITLE
Exception came after long time

### ISSUE THREAD

**Issue by ns-psingh** [ns-psingh/covid_notifier#7]
`Traceback (most recent call last):
  File "mac_notify.py", line 28, in <module>
    covid.retreive()
  File "/Documents/covid_notif/covid_notifier/covid_data.py", line 22, in retreive
    response = requests.get(url)
  File "/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))`

**Comment by shobhit-kumar-code** [comment]
Is it due to a network connectivity issue?

**Comment by ns-psingh** [comment]
Could be, not sure.
